### ISSUE TITLE
error, urllib2 related?

### ISSUE THREAD

**Issue by rootexpression** [wise-king-sullyman/bitcoin_price_alert#1] opened 2017-06-09 00:50 UTC
> $ python2 bitcoin_price_alert.py 
Traceback (most recent call last):
  File "bitcoin_price_alert.py", line 77, in <module>
    url = urllib2.urlopen("http://api.coindesk.com/v1/bpi/currentprice.json").read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 520: Origin Error

I verified at coindesk's site that the api location is correct and that I had an up-to-date urllib2.  Don't know what else to try.

**Comment by wise-king-sullyman** [comment] 2017-06-09 22:39
Hi sorry I actually have just updated the code with what I believe fixes it. It was a stupid mistake on my part that I think is fixed now. Will have to test to confirm. You can see the fix on lines 121 and 122 now.

**Comment by rootexpression** [comment] 2017-06-10 07:26
I am excited to put this into use.  It works perfectly with the two lines
fixed.

Thanks for making this available, and being so open to helping.

**Comment by wise-king-sullyman** [comment] 2017-06-10 10:09
@rootexpression not a problem. I've reaped the benefits from others open source projects for years so I figured it was time I gave back. 

Let me ask you, if I updated this with things like multiple coin tracking, and a gui would you find that useful? I've been thinking about doing a major update to this for a while but I didn't figure anyone was using it.

**Comment by rootexpression** [comment] 2017-06-11 04:34
I would certainly find both of those features useful.

I'll be sure to share any useful additions or changes I make going along as
well.  So far, the only thing I could share is the addition of generating a
.pid file to track the status of the program, though its a bit of a hack
job and not worthy of incorporating.

**Closed as completed** 2017-06-11 13:05 UTC

**Comment by wise-king-sullyman** [comment] 2017-06-11 13:08
@rootexpression any collaboration on this is more than welcome. Also I am going to go ahead and close this issue as you said the problem is fixed. 

I would be interested in at least looking over your additions as well, maybe adding them to the main branch. Get up with me on the email I listed in the readme if you're really interested in sharing them.
